apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project
  labels:
    app: devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
        - name: devops-project
          image: acrfordevopspoc01adrian.azurecr.io/devops-project:1.0.3
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "test"
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"


