apiVersion: v1
kind: Service
metadata:
  name: devops-project
  labels:
    app: devops-project
spec:
  selector:
    app: devops-project
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
